Fix lower-constraints CI error
ooking in indexes: https://mirror.gra1.ovh.opendev.org/pypi/simple, https://mirror.gra1.ovh.opendev.org/wheel/ubuntu-20.04-x86_64
Collecting hacking<3.1.0,>=3.0.1
  Downloading https://mirror.gra1.ovh.opendev.org/pypifiles/packages/d8/1e/87943c48e3bcd6010d2539130f322168e46186429ae4d26128d7cf496d13/hacking-3.0.1-py3-none-any.whl (37 kB)
Collecting coverage>=4.5.1
  Downloading https://mirror.gra1.ovh.opendev.org/wheel/ubuntu-20.04-x86_64/coverage/coverage-4.5.1-cp38-cp38-linux_x86_64.whl (214 kB)
Collecting stestr>=2.0.0
  Downloading https://mirror.gra1.ovh.opendev.org/wheel/ubuntu-20.04-x86_64/stestr/stestr-2.0.0-py3-none-any.whl (102 kB)
Collecting testtools>=2.2.0
  Downloading https://mirror.gra1.ovh.opendev.org/wheel/ubuntu-20.04-x86_64/testtools/testtools-2.2.0-py2.py3-none-any.whl (195 kB)
ERROR: Cannot install astroid==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested astroid==2.1.0
    The user requested (constraint) astroid==1.6.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Change-Id: I65a5acd0ed5188c7810200eaeefd55a0030d6eda